version: "2"
services:
  app:
    restart: always
    image: guydw/eggchatbackend:latest
    ports:
      - "8080:8080"
    links:
      - mongo
    expose:
      - "5000"
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017"
